BehrBlog/Models/Picts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;


namespace BehrBlog.Models
{
    public class Picts
    {
        public int ID { get; set; }
        public int PostFK { get; set; }
        public string PicTitle { get; set; }
        public string EditDate { get; set; }
        public string PictPict { get; set; }
    }
}

BehrBlog/Controllers/PictsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BehrBlog.Models;
using System.IO;


namespace BehrBlog.Controllers
{
    public class PictsController : Controller
    {
        private PostDbContext db = new PostDbContext();

        // GET: Picts
        public ActionResult Index(string searchString)
        {
            var picts = from q in db.Picts
                        select q;

            if (!String.IsNullOrEmpty(searchString))
            {
                picts = picts.Where(r => r.PostFK.Equals(searchString));
            }

            return View(db.Picts.ToList());
        }

        //// GET: Picts/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Picts picts = db.Picts.Find(id);
        //    if (picts == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(picts);
        //}

        // GET: Picts/Create
        public ActionResult Create(int? fkid)
        {
            if (fkid == null)
                {
                ViewBag.fkid = "no post attached, go back!!!";
                }

            ViewBag.fkid = fkid;

            return View();
        }

        // POST: Picts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PostFK,PicTitle,EditDate,PictPict")] Picts picts)
        {

            var file = Request.Files[0];
            var sessUnq = Session.SessionID.Substring(Session.SessionID.Length - 4);
            if (file != null && file.ContentLength > 0)
            {
                var fileName = sessUnq + Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/UploadPictures/"), fileName);
                file.SaveAs(path);
                picts.PictPict = fileName;
            }

            if (ModelState.IsValid)
            {
                //picts.PostFK = ViewBag.aId;

                String aDate = DateTime.UtcNow.ToString("yyMMddHHmmss");
                picts.EditDate = aDate;

                db.Picts.Add(picts);
                db.SaveChanges();

                int fkid = picts.PostFK;

                return RedirectToAction("Details","Main", new { id = fkid });
                //return RedirectToAction("Index");
            }

            return View(picts);
        }

        // GET: Picts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picts picts = db.Picts.Find(id);
            if (picts == null)
            {
                return HttpNotFound();
            }
            return View(picts);
        }

        // POST: Picts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PostFK,PicTitle,EditDate,PictPict")] Picts picts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(picts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(picts);
        }

        // GET: Picts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picts picts = db.Picts.Find(id);
            if (picts == null)
            {
                return HttpNotFound();
            }
            return View(picts);
        }

        // POST: Picts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Picts picts = db.Picts.Find(id);

            int fkid = picts.ID;

            string fullPath = Request.MapPath("~/Images/Cakes/" + picts.PictPict);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }

            db.Picts.Remove(picts);
            db.SaveChanges();


            return RedirectToAction("Details", "Main", new { id = fkid });
            //return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BehrBlog/Views/Picts/Create.cshtml
@model BehrBlog.Models.Picts

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Picts", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picts</h4>
        <b>Adding a picture for Post Number: @ViewBag.fkid</b>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PostFK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostFK, new { htmlAttributes = new { @class = "form-control", @Value = @ViewBag.fkid } })
                @Html.ValidationMessageFor(model => model.PostFK, "", new { @class = "text-danger" })
                <b>***DONT TOUCH THIS VALUE***</b>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PicTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PicTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PicTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.EditDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EditDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EditDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.PictPict, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input type="file" name="file" class="form-control" />

                @*@Html.EditorFor(model => model.PictPict, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.PictPict, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Post Details", "Details","Main", new { id = ViewBag.fkid }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BehrBlog/Views/Picts/Delete.cshtml
@model BehrBlog.Models.Picts

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Picts</h4>
    <hr />
    <dl class="dl-horizontal">

        <dd>
            @Html.DisplayFor(model => model.PicTitle)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.PictPict)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BehrBlog/Views/Picts/Details.cshtml
@model BehrBlog.Models.Picts

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Picts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PostFK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostFK)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PicTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PicTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EditDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EditDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PictPict)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PictPict)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BehrBlog/Views/Picts/Edit.cshtml
@model BehrBlog.Models.Picts

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PostFK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostFK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PicTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PicTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PicTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EditDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EditDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EditDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PictPict, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PictPict, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PictPict, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BehrBlog/Views/Picts/Index.cshtml
@model IEnumerable<BehrBlog.Models.Picts>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
    @using (Html.BeginForm())
    {
    }

    <p>
        Post ID: @Html.TextBox("SearchString") <br />
    </p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PostFK)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PicTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EditDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PictPict)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PostFK)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PicTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EditDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PictPict)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.ID }) |*@
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>